site_name: Treinamento HTML & CSS
theme: readthedocs
extra_css: []
pages:
- Home: index.md
- HTML: html/index.md
- CSS: css/index.md
- HTML5: html5/index.md
- CSS3: css3/index.md
- Design Responsivo: responsive/index.md
